- LICENSE
🔖 Added a LICENSE file so people know how to use this repository.
> 🔖 Added a LICENSE file

- README.md
💬 Updated the contributing information to show new users how to contribute to this repository.
> 💬 Updated the contributing information

- CONTRIBUTING.md
🔖 Added a CONTRIBUTING.md file so it's easier for new users to contribute to this repository.
> 🔖 Added a CONTRIBUTING.md file

- commands/giveaway.js
🐛 Fixed the bug that skipped this line of code.
> 🐛 Fixed a bug

- README.md
hey, i found a typo while scrolling through this repo, hope this helps :)
> fix typo_lol

- README.md
- commands/giveaway.js
- commands/help.js
✨ Added new time variables to choose from.
🐛 Fixed old time bug.
> ✨ 🐛 Added new time variables, fixed time bug

- README.md
- Added a reworked version of the old README.md
> Giveaway-Bot v1.2.2 [patch]

- commands/help.js
> Giveaway-Bot v1.2.3 [patch]

- README.md
- commands/help.js
- package.json
✏️ Updated all GitHub links and author names.
> ✏️ Updated links & names

- commands/end.js
- commands/help.js
- commands/reroll.js
- commands/start.js
changing "manage messages" to "\`MANAGE_MESSAGES\`" and fixing errors that i could see
> ✏️ 🎨 Fixed spelling, added markdown

- commands/start.js
changed prize to giveawayPrize otherwise you get an error saying prize isn't defined
> change prize to giveawayPrize

- commands/start.js
would've been hard for people to understand "i didn't get a number from this" etc.
> make it more understandable

- README.md
change repositroy to repository
> Little spelling error

- setup.bat
> ⚙️ Added setup.bat file

- README.md
the file is actually called start not start-bot
> isn't start-bot

- commands/start.js
> add parseInt()

- README.md
this will mean i can push updates if i need to do so. and also close issues etc
> maybe give me full access?!?!

- README.md
- commands/Giveaways/start.js
- config.json
```json
"Giveaway_Options": {
"showMention": true,
"hostedBy": true
}
```
If "showMention: true" the bot will display the giveaway as:
<div align="center">
</div>
```json
"Giveaway_Options": {
"showMention": false,
"hostedBy": true
}
```
However, if "showMention: false" the bot will send @everyone then will delete it a second later leaving it like this:
<div align="center">
<br>
<br>
<br>
<br>
<strong><i>NOTE: showMention will default to true.</i></strong>
</div>
<br>
<br>
<strong><i>What config.json will look like with values:<i/></strong>
```json
{
"Bot_Info": {
"token": "MTdqrd0vGDV1dcF0QPjom6OB.NQxUhj.I4JjFHIympR3mVF3UiUbbD5VVbi",
"prefix": "!"
},
"Embed_Defaults": {
"EmbedColour": "RANDOM"
},
"Giveaway_Options": {
"giveawayRoleID": "846135298185756692",
"showMention": true, …
```
> Add new options in config.json

- README.md
- commands/Giveaways/start.js
- config.json
* Add new features
* update gif and json table
* update adding ID
> Add new options in config.json (#72)

- README.md
- Added steps for Windows and Linux
- Cleaner tables
- Complete steps for using the zip file to install
- Fix some typo
> Made a better readme

- README.md
I'm archiving this repository because it's way to outdated for the discord.js package and I don't really feel like working on it anymore.
>  ⚠️ Outdated ⚠️
